#!/bin/sh

corpus=${1:?}

\rm -r report
find -L ${corpus} -regextype posix-extended -regex '.*/(pre|post)(inst|rm)' | \
    bin/shstats \
	--specification share/specification.org\
	--report-path report
